-- ====================================================================
--  SUPABASE SCHEMA SETUP — AKV Admin Dashboard
--  Jalankan SQL ini di Supabase SQL Editor (Dashboard > SQL Editor)
-- ====================================================================

-- 1. Tabel contact (single row, id=1)
create table if not exists public.contact (
  id int primary key default 1 check (id = 1),
  whatsapp text not null default '',
  instagram text not null default '',
  tiktok text not null default '',
  email text not null default ''
);

-- 2. Tabel services
create table if not exists public.services (
  id int primary key generated by default as identity,
  icon text not null default 'sparkles',
  title text not null default '',
  "desc" text not null default ''
);

-- 3. Tabel portfolio_items
create table if not exists public.portfolio_items (
  id int primary key generated by default as identity,
  title text not null default '',
  category text not null default '',
  image text,
  tone text not null default 'from-akv-blue to-akv-royal'
);

-- 4. Tabel testimonials
create table if not exists public.testimonials (
  id int primary key generated by default as identity,
  name text not null default '',
  role text not null default '',
  quote text not null default ''
);

-- 5. Tabel team_members
create table if not exists public.team_members (
  id int primary key generated by default as identity,
  name text not null default '',
  role text not null default '',
  url text not null default ''
);

-- ====================================================================
--  ROW LEVEL SECURITY (RLS)
--  - Public SELECT untuk semua tabel (landing page bisa baca)
--  - INSERT/UPDATE/DELETE hanya untuk authenticated users (admin)
-- ====================================================================

-- contact
alter table public.contact enable row level security;

create policy "Public read contact"
  on public.contact for select
  to anon, authenticated
  using (true);

create policy "Admin insert contact"
  on public.contact for insert
  to authenticated
  with check (true);

create policy "Admin update contact"
  on public.contact for update
  to authenticated
  using (true)
  with check (true);

create policy "Admin delete contact"
  on public.contact for delete
  to authenticated
  using (true);

-- services
alter table public.services enable row level security;

create policy "Public read services"
  on public.services for select
  to anon, authenticated
  using (true);

create policy "Admin insert services"
  on public.services for insert
  to authenticated
  with check (true);

create policy "Admin update services"
  on public.services for update
  to authenticated
  using (true)
  with check (true);

create policy "Admin delete services"
  on public.services for delete
  to authenticated
  using (true);

-- portfolio_items
alter table public.portfolio_items enable row level security;

create policy "Public read portfolio_items"
  on public.portfolio_items for select
  to anon, authenticated
  using (true);

create policy "Admin insert portfolio_items"
  on public.portfolio_items for insert
  to authenticated
  with check (true);

create policy "Admin update portfolio_items"
  on public.portfolio_items for update
  to authenticated
  using (true)
  with check (true);

create policy "Admin delete portfolio_items"
  on public.portfolio_items for delete
  to authenticated
  using (true);

-- testimonials
alter table public.testimonials enable row level security;

create policy "Public read testimonials"
  on public.testimonials for select
  to anon, authenticated
  using (true);

create policy "Admin insert testimonials"
  on public.testimonials for insert
  to authenticated
  with check (true);

create policy "Admin update testimonials"
  on public.testimonials for update
  to authenticated
  using (true)
  with check (true);

create policy "Admin delete testimonials"
  on public.testimonials for delete
  to authenticated
  using (true);

-- team_members
alter table public.team_members enable row level security;

create policy "Public read team_members"
  on public.team_members for select
  to anon, authenticated
  using (true);

create policy "Admin insert team_members"
  on public.team_members for insert
  to authenticated
  with check (true);

create policy "Admin update team_members"
  on public.team_members for update
  to authenticated
  using (true)
  with check (true);

create policy "Admin delete team_members"
  on public.team_members for delete
  to authenticated
  using (true);

-- ====================================================================
--  SEED DATA — isi bawaan dari site.js
-- ====================================================================

insert into public.contact (id, whatsapp, instagram, tiktok, email) values
  (1, '6281234567890', 'https://instagram.com/akuvisual.id', 'https://tiktok.com/@akuvisual.id', 'halo@akv.zakariamp.id')
on conflict (id) do nothing;

insert into public.services (id, icon, title, "desc") values
  (1, 'palette',   'Desain Grafis',          'Poster, banner, feed, dan kebutuhan visual harian yang rapi dan konsisten.'),
  (2, 'badge',     'Branding dan Logo',      'Identitas visual lengkap: logo, warna, dan guideline yang siap dipakai.'),
  (3, 'file',      'CV dan Portofolio',      'CV ATS-friendly dan portofolio yang bikin profilmu tampil menonjol.'),
  (4, 'globe',     'Website Portofolio',     'Website personal atau bisnis yang responsif, cepat, dan mudah dikelola.'),
  (5, 'sparkles',  'AI Visual Branding',     'Eksplorasi visual berbasis AI yang tetap diarahkan dengan sentuhan desainer.'),
  (6, 'film',      'Animasi AI',             'Animasi pendek untuk intro brand, konten, dan presentasi yang hidup.'),
  (7, 'video',     'Editing Video',          'Editing reels, konten pendek, dan video promosi dengan pacing yang pas.'),
  (8, 'megaphone', 'Konten Media Sosial',    'Template feed dan konten sosial media yang terarah dan on-brand.')
on conflict (id) do nothing;

insert into public.portfolio_items (id, title, category, image, tone) values
  (1, 'Feed Instagram UMKM',        'Desain',            null, 'from-akv-blue to-akv-royal'),
  (2, 'Logo & Brand Kit',           'Branding',          null, 'from-akv-royal to-akv-navy'),
  (3, 'CV Kreatif Mahasiswa',       'CV dan Portofolio', null, 'from-akv-sky to-akv-blue'),
  (4, 'Website Portofolio Personal','Website',           null, 'from-akv-blue to-akv-sky'),
  (5, 'Animasi Intro Brand',        'Animasi',           null, 'from-akv-navy to-akv-blue'),
  (6, 'Poster Event Kampus',        'Desain',            null, 'from-akv-royal to-akv-sky'),
  (7, 'Rebranding Organisasi',      'Branding',          null, 'from-akv-blue to-akv-navy'),
  (8, 'Landing Page UMKM',          'Website',           null, 'from-akv-sky to-akv-royal')
on conflict (id) do nothing;

insert into public.testimonials (id, name, role, quote) values
  (1, 'Naj***', 'Mahasiswa',           'CV sama portofolio aku dirapikan sampai enak banget dilihat. Pas interview, desainnya sempat dipuji HRD.'),
  (2, 'Az**',   'Pemilik UMKM',        'Feed toko jadi konsisten satu gaya. Pelan-pelan makin banyak yang nanya produk lewat Instagram.'),
  (3, 'Ra***',  'Ketua Organisasi',     'Desain buat event kami selalu selesai sebelum deadline. Komunikasinya enak, revisinya juga cepat.'),
  (4, 'Di**',   'Personal Brand',       'Website portofolioku cepat jadi, rapi di HP maupun laptop, dan gampang aku update sendiri.'),
  (5, 'Fa***',  'Panitia Event Kampus', 'Poster dan feed event langsung kelihatan profesional. Diajak diskusi konsep juga nyambung.'),
  (6, 'Sal**',  'Content Creator',      'Editing video dan template konten dari AKV bikin jadwal posting aku jauh lebih ringan.')
on conflict (id) do nothing;

insert into public.team_members (id, name, role, url) values
  (1, 'Lia Nur Khasanah',       'Founder · Creative Director',    'https://lianurkhasanah.my.id'),
  (2, 'Zakaria Mujur Prasetyo', 'Co-Founder · Visual Designer',   'https://zdekktech.biz.id/about')
on conflict (id) do nothing;
